import React from 'react';
import {Heart,MessageCircle,Eye,Bookmark,ChevronRight,Search} from 'lucide-react';
import {EmptyState} from '../../components/shared/States.jsx';
import UserSearch from './UserSearch.jsx';
import SeasonalOverlay from '../seasonal/SeasonalOverlay.jsx';
function timeLeft(post){if(post.mode==='once')return post.viewed?'expired':'view once';const left=Math.max(0,1440-post.postedMinutesAgo);return left<=0?'expired':`${Math.floor(left/60)}h ${left%60}m left`}
const gradients=['linear-gradient(145deg,#2f3a40,#12161b)','linear-gradient(145deg,#493221,#17120e)','linear-gradient(145deg,#293f39,#111816)','linear-gradient(145deg,#3b293d,#17121a)'];
export function DumpCard({post,onOpen}){const expired=timeLeft(post)==='expired';return <button className="card post-card" onClick={()=>!expired&&onOpen(post)} style={{width:'100%',textAlign:'left',opacity:expired?.45:1}}><div className="post-media" style={{background:gradients[post.id%gradients.length]}}><div><span className="tag">{post.mood}</span><div className="media-text" style={{marginTop:10}}>{post.items.length} moments</div></div><span className="tag flicd-mono" style={{marginLeft:'auto',alignSelf:'flex-start',color:post.mode==='once'?'var(--danger)':'var(--amber)'}}>{post.mode==='once'&&<Eye size={11} style={{marginRight:4}}/>}{timeLeft(post)}</span></div><div className="meta"><div><strong>@{post.author}</strong><div className="subtitle" style={{marginTop:3}}>{post.context||'shared a moment'}</div></div><div className="row muted"><span className="row"><Heart size={14} fill={post.liked?'var(--amber)':'none'} color={post.liked?'var(--amber)':'currentColor'}/>{post.likes}</span><span className="row"><MessageCircle size={14}/>{post.comments.length}</span></div></div></button>}
export default function Home({dumps,activeSpace,onOpen}){const [searchOpen,setSearchOpen]=React.useState(false);const visible=dumps.filter(d=>d.channel===activeSpace.id);return <div className="screen" style={{position:'relative'}}><SeasonalOverlay/><div className="topbar"><div><div className="eyebrow">Flic'd / {activeSpace.label}</div><h1 className="title">Your moments</h1><p className="subtitle">Following from @{activeSpace.handle}.</p></div><div className="row"><div className="tag flicd-mono">{activeSpace.followers} followers</div><button type="button" className="btn icon-btn" onClick={()=>setSearchOpen(true)} aria-label="Search users"><Search size={19}/></button></div></div><div className="stack">{visible.length===0?<EmptyState title="Nothing here yet" text="Follow people from this space or create a new dump."/>:visible.map(p=><DumpCard key={p.id} post={p} onOpen={onOpen}/>)}</div>{searchOpen&&<UserSearch onClose={()=>setSearchOpen(false)}/>}</div>}
export function Viewer({post,onClose,onLike,onComment,onKeep,onMarkViewed}){const [text,setText]=React.useState('');const [index,setIndex]=React.useState(0);React.useEffect(()=>{onMarkViewed(post.id)},[post.id]);const item=post.items[index];return <div className="screen" style={{paddingBottom:28}}><div className="topbar"><button className="btn icon-btn" onClick={onClose} aria-label="Close">×</button><span className="tag flicd-mono">{timeLeft(post)}</span></div><div className="card"><div className="post-media" style={{background:gradients[(post.id+index)%gradients.length],aspectRatio:'1/1'}}><div><span className="tag">@{post.author} · {post.mood}</span><div className="media-text" style={{marginTop:12}}>{item?.note||'a little piece of the day'}</div></div></div>{post.items.length>1&&<div className="row" style={{justifyContent:'space-between',marginTop:10}}><button className="btn" disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ChevronRight size={16} style={{transform:'rotate(180deg)'}}/></button><span className="flicd-mono muted">{index+1}/{post.items.length}</span><button className="btn" disabled={index===post.items.length-1} onClick={()=>setIndex(i=>i+1)}><ChevronRight size={16}/></button></div>}<div className="meta"><button className="btn" onClick={()=>onLike(post.id)}><Heart size={16} fill={post.liked?'var(--amber)':'none'} color={post.liked?'var(--amber)':'currentColor'}/>{post.likes}</button><button className="btn" onClick={()=>onKeep(post,index)}><Bookmark size={16}/>Keep</button></div><div className="stack" style={{marginTop:16}}>{post.comments.length?<>{post.comments.map(c=><p key={c.id} className="subtitle"><strong style={{color:'var(--text)'}}>@{c.from}</strong> {c.text}</p>)}</>:<p className="subtitle">No comments yet.</p>}</div><div className="row" style={{marginTop:14}}><input className="input" value={text} onChange={e=>setText(e.target.value)} placeholder="Add a comment"/><button className="btn btn-primary" disabled={!text.trim()} onClick={()=>{onComment(post.id,text.trim());setText('')}}>Send</button></div></div></div>}
